Add Navigation For list and More
Listify-Market-Team/Listify-Market-Frontend pull request #13
Opened 2022-11-17 17:40 UTC by Maestroabel

Add switch AddProductScreen to ListScreen
Add SpinnerCircular in Node_module
Add SpinnerCircular as a Load Screen

2022-11-22 23:58 UTC, Almsrr requested changes
Elimina el package-lock.json file

2022-11-22 23:58 UTC, alamsierrad commented on .yarnrc.yml
> +nodeLinker: node-modules
De donde sale este archivo?

2022-11-22 23:58 UTC, Almsrr commented on components/List.js
> +      console.log(user.id);
Elimina los logs de todas partes, no solo este

2022-11-22 23:58 UTC, Almsrr commented on components/List.js
> +    const unsubscribe = props.navigation.addListener("focus", () => {
Por que un focus event?

2022-11-22 23:58 UTC, Almsrr commented on components/List.js
>        const res = await fetch("https://listifym-backend.herokuapp.com/api/Inventory/GetByUserId?userID="+user.id);
Aqui usa las constantes que se crearon para la url del API

2022-11-22 23:58 UTC, Almsrr commented on components/ProductToList/PressComponents.js
> +            console.log(data);
Este es otro log

2022-11-23 00:08 UTC, Maestroabel commented on components/List.js
> +    const unsubscribe = props.navigation.addListener("focus", () => {
Esto no sé exactamente, pero no lo agregué yo. Estaba agregado luego del los cambios del Navigate

2022-11-23 00:12 UTC, Maestroabel commented on components/List.js
>        const res = await fetch("https://listifym-backend.herokuapp.com/api/Inventory/GetByUserId?userID="+user.id);
Las constantes están agregadas ya en Develop. Yo hice el merge en mi rama.

2022-11-23 00:12 UTC, Maestroabel commented on components/ProductToList/PressComponents.js
> +            console.log(data);
Borrado.

2022-11-23 00:33 UTC, Maestroabel commented on .yarnrc.yml
> +nodeLinker: node-modules
Eso creo que es del Yarn, al instalarlo

2022-11-23 00:33 UTC, Almsrr commented on .yarnrc.yml
> +nodeLinker: node-modules
Puedes quitarlo

2022-11-23 00:34 UTC, Almsrr commented on components/List.js
> +    const unsubscribe = props.navigation.addListener("focus", () => {
Ok

2022-11-23 00:34 UTC, Almsrr commented on components/List.js
>        const res = await fetch("https://listifym-backend.herokuapp.com/api/Inventory/GetByUserId?userID="+user.id);
Si hiciste merge se supone que esta ahi ya

2022-11-23 00:44 UTC, Almsrr approved these changes

2022-11-23 00:44 UTC, merged